local Games = Window:NewTab("Games", 12689980465)
local GamesSection = Games:NewSection("Games")
GamesSection:NewButton("Da Hood", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(2788229376, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Arsenal", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(286090429, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Tower of Hell", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(1962086868, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("KAT", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(621129760, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Fencing", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(12109643, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Work at a Pizza Place", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(192800, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("VR Hands", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(4832438542, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Adopt Me!", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(920587237, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Jailbreak", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(606849621, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Prison Life", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(155615604, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Build A Boat For Treasure", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(537413528, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Gorilla Tag Professional", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(8690998110, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Murder Mystery 2", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(142823291, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Blox Fruits", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(2753915549, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Counter Blox", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(301549746, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Mic Up", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(6884319169, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Neighbors", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(12699642568, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Natural Disaster Survival", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(189707, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Ro-Ghoul", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(914010731, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Blade Ball", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(13772394625, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Pet Simulator X", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(13772394625, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Pet Simulator 99", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(8737899170, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Legends Of Speed", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(3101667897, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Brookhaven RP", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(4924922222, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Bedwars", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(6872265039, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("CHAOS", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(6441847031, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Ninja Legends", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(3956818381, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Bayside High School", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(12640491155, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("BIG Paintball!", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(3527629287, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("BIG Paintball 2!", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(9865958871, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Muscle Legends", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(3623096087, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Road to Grambys", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(5796917097, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Bloxburg", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(185655149, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Cursed Sea", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(14426444782, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Doors", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(6516141723, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Hide and Seek Extreme", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(205224386, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Life in Paradise", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(1662219031, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Adopt and Raise a Baby", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(383793228, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Zombie Attack", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(1240123653, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Super Simon Says", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(61846006, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Life Sentence", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(13083893317, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Rainbow Friends", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(7991339063, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Infectious Smile", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(5985232436, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Colony Survival", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(14888386963, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Red Light, Green Light", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(7540891731, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("3008", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(2768379856, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("Guess the drawing!", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(3281073759, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("VR Hangout", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(8769714622, game:GetService("Players").LocalPlayer)
end)
GamesSection:NewButton("VR Hands Legacy", "Teleports you to game", function()
	queueteleport("loadstring(game:HttpGet('https://raw.githubusercontent.com/yofriendfromschool1/Sky-Hub/main/SkyHub.txt'))()")
	game:GetService("TeleportService"):Teleport(16912831373, game:GetService("Players").LocalPlayer)
end)